# All Targets
all: AntiVirus hexaPrint

# Tool invocations
AntiVirus: 
	gcc -m32 -g -Wall -o AntiVirus AntiVirus.c

hexaPrint:
	gcc -m32 -g -Wall -o hexaPrint hexaPrint.c
	
# Other Targets
clean:
	rm -f AntiVirus hexaPrint *.o